services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      - CODESPACE_NAME=${CODESPACE_NAME}
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - VITE_GOOGLE_CLIENT_ID=314182030840-i0cgg6jc56sfpqndsco0djd3tff18958.apps.googleusercontent.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh /app/start.sh
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
